### PR TITLE
Fix tests, add code coverage reports

### PR DESCRIPTION
**Pull request by StevenACoffman**
- Fix tests by excluding ServletTestExecutionListener, DirtiesContextTestExecutionListener, TransactionalTestExecutionListener, SqlScriptsTestExecutionListener from TestExecutionListeners\
- Add jacoco and cobertura test coverage, nicer test console output, html reports

Spring4 Test framework can't instantiate some of the default test listeners since they aren't on the classpath.  ServletTestExecutionListener and TransactionalTestExecutionListener in particular cause problems. The other ones I excluded aren't harmful, but aren't needed.

I used your example as the basis of my project, so I thought I'd backport my fixes to your example. Thanks for helping me out by having shared this project.

### CODE REVIEW

**Comment by larixer** [comment]
Thanks Steve!

That was the reason to create example - to help setting up Groovy-based projects.

**Comment by larixer** [comment]
Steve, I had an intention to switch license of this project to public domain, so that people do not have any troubles in reusing this code in own projects. But seems there are still remnants of Apache 2 license remaining. Will it be okay with you if I will clean up Apache 2 remnants and leave only public domain license?

**Comment by StevenACoffman** [comment]
Sure. I hereby give you permission to change the license to whatever you like now or in the future. :)

Thanks again for sharing something that helped me out when I needed it.

**Comment by larixer** [comment]
Thanks Steve!

**Pull request merged**
